### Workout Tracker API - HTTP Requests
DELETE {{baseUrl}}/exercises/1
### Delete Exercise

}
  "weight": 100.0
  "reps": 5,
  "sets": 5,
  "name": "Heavy Bench Press",
{

Content-Type: application/json
PATCH {{baseUrl}}/exercises/1
### Update Exercise (Full Update)

}
  "weight": null
{

Content-Type: application/json
PATCH {{baseUrl}}/exercises/1
### Update Exercise (Convert to Bodyweight)

}
  "reps": 6
  "sets": 5,
{

Content-Type: application/json
PATCH {{baseUrl}}/exercises/1
### Update Exercise (Partial - Change Sets and Reps)

}
  "weight": 85.0
{

Content-Type: application/json
PATCH {{baseUrl}}/exercises/1
### Update Exercise (Partial - Change Weight)

}
  "reps": 10
  "sets": 3,
  "name": "Pull-ups",
{

Content-Type: application/json
POST {{baseUrl}}/exercises
### Create Bodyweight Exercise (No Weight)

}
  "weight": 80.0
  "reps": 8,
  "sets": 4,
  "name": "Bench Press",
{

Content-Type: application/json
POST {{baseUrl}}/exercises
### Create New Exercise (Weighted)

GET {{baseUrl}}/exercises/1
### Get Exercise by ID

GET {{baseUrl}}/exercises
### Get All Exercises

GET {{baseUrl}}/
### Health Check / Root

@baseUrl = http://localhost:8000

### Use with VS Code REST Client extension or JetBrains HTTP Client

